/**
 * Authentication Configuration
 * Auto-generated by Simplita
 */

export interface AuthConfig {
  protectedPages: string[];
  loginPage: string;
  publicPages: string[];
  redirectAfterLogin?: string;
}

export const authConfig: AuthConfig = {
  protectedPages: [

  ],
  loginPage: '/login',
  publicPages: [
  '/orientation-calls',
  '/form-submission',
  '/sign-up',
  '/chat-history',
  '/login',
  '/userdirectory',
  '/chatbot',
  '/dashboard',
  '/'
  ],
  redirectAfterLogin: undefined,
};

export function isProtectedPage(pathname: string): boolean {
  return authConfig.protectedPages.some(
    protectedPath => pathname === protectedPath || pathname.startsWith(protectedPath + '/')
  );
}

export function isPublicPage(pathname: string): boolean {
  return authConfig.publicPages.some(
    publicPath => pathname === publicPath || pathname.startsWith(publicPath + '/')
  );
}

export function isLoginPage(pathname: string): boolean {
  if (!authConfig.loginPage) return false;
  return pathname === authConfig.loginPage || pathname.startsWith(authConfig.loginPage + '/');
}
